export const searchData = [
  {
    'path': '/',
    'title': 'Welcome to Brace.to documentation',
    'sections': [
      [
        '',
        '',
        [
          "Our documentation is designed to empower you, helping you understand Brace.to's features, navigate its interface, and troubleshoot any issues you may encounter. Whether you're getting started, aiming for mastery, or facing challenges, our documentation will help you achieve what you want.",
        ],
      ],
      [
        'Brace.to: The TL;DR',
        'brace-to-the-tl-dr',
        [
          'Brace.to is your bookmark manager with privacy at heart. Brace.to helps you save links to everything and visit them later easily, anytime, on any of your devices. Powered by Stacks technology, all your saved links are encrypted, and only you can decrypt them and see the content inside.',
          'There are several ways to save a link for your convenience. You can save a link:',
          'At our website (https://brace.to)',
          'In the web browser address bar by typing "brace.to" and "/" before any link',
          'With our web browser extensions on your desktop',
          'Via our mobile apps on your phone',
          'Then, you can visit your saved links anytime on any of your devices. Every link you save will be beautified with its representative image and title so you can easily find and recognize it.',
          'Powered by Web3 technology from Stacks:',
          'Your account is cryptographically generated; only you, with your Secret Key, can control it. Your account cannot be locked, banned, or deleted by anyone, as your Secret Key is required to access and modify your account.',
          'Everything is encrypted; only you, with your Secret Key, can see the content inside. No one can see the content inside your data, so it cannot be used to create targeted ads. If your data is stolen, no information is leaked.',
          'Your data lives in a data server of your choice; only you, with your Secret Key, can change it. You can manage your data and set permissions directly, as you can host your own data server or choose any data server provider.',
          "Bring back control of your account and data one link at a time with Brace.to, powered by Web3 technology from Stacks, to ensure your privacy cannot be compromised. Not only that Brace.to doesn't be evil; Brace.to can't be.",
          'Brace.to offers one simple no-tricks subscription plan to support us and unlock all extra features:',
          'Tags',
          'Lock lists',
          'Change title & image',
          'Dark appearance',
          'Pin to the top',
          "It's our intention to never show advertisements, and we don't rent, sell, or share your information with other companies. Our optional paid subscription is the only way we make money.",
        ],
      ],
      [
        'How to Use These Docs',
        'how-to-use-these-docs',
        [
          'You can start by reading through the topics in the left-hand navigation or jump directly to specific areas that interest you. If you want something specific, use the search function (Cmd/Ctrl + K) to find articles with particular keywords.',
        ],
      ],
      [
        'What Next?',
        'what-next',
        [
          "Brace.to's Features",
          "Looking to learn more about Brace.to's features? The \"Features\" section in the left navigation is where you want to go. This section explains everything Brace.to offers, from its core functionalities to extra features. Whether you are a new user or a pro, the Features section will help you know everything to utilize and unlock Brace.to's full potential.",
          'Basic Concepts',
          'Are you new to bookmarking or read-later apps? The "Brace.to 101" section is a great place to start. This introductory section explains what a bookmark manager is and how it differs from a read-later app.',
          'Misc.',
          "This \"Misc.\" section contains FAQs or Frequently Asked Questions. If you have any questions about Brace.to, this is an excellent place to start. Our FAQs section covers various topics, from general usage to feature functionality. If you can't find the answer you want here, don't hesitate to contact us.",
        ],
      ],
    ],
  },
  {
    'path': '/account',
    'title': 'Account',
    'sections': [
      [
        '',
        '',
        [
          'Your account is cryptographically generated; only you, with your Secret Key, can control it.',
          "When you use Brace.to, your account is cryptographically generated. You'll receive a Secret Key — a unique set of 24 words that acts like a password — used to derive your account with cryptographic algorithms. Only you know your Secret Key and only your Secret Key can be used to create your account and make changes to it. Your account cannot be locked, banned, or deleted by anyone, as your Secret Key is required to access and modify your account.",
        ],
      ],
      [
        'Stacks Account',
        'stacks-account',
        [
          'Your account is a Stacks account, and a Stacks account is used to access the Stacks blockchain and a Stacks data server. The Stacks blockchain stores your account information, such as your username, profile, and data server location. A Stacks data server stores your encrypted app data, such as all your saved links.',
          "Your Secret Key acts like a password. It's only known to you, ensuring that only you can decrypt your data and see the content inside. If you lose it, there is no way to retrieve it back. You need to keep it safe.",
          "Your Secret Key cannot be changed or reset. As it's used to encrypt your content file by file, if you change your Secret Key, every file needs to be decrypted with your old Secret Key and encrypted again with your new Secret Key.",
        ],
      ],
      [
        'Delete Account',
        'delete-account',
        [
          "No one without your Secret Key can access your account or content, so you don't need to delete them. To delete all your data, please go to Settings → Data → Delete All Data.",
          'Your Stacks account is generated by a cryptographic algorithm and your Secret Key. Forgetting your Secret Key is the only way to delete your account.',
          "If you've started with us, we create your Stacks account without a username, profile, or data server location. So, no data is stored in the Stacks blockchain, and your data is stored in our provided server by default.",
          "After you delete all your data in Settings → Data → Delete All Data, there's nothing left. You can forget your Secret Key. It's permanently deleting your account.",
        ],
      ],
    ],
  },
  {
    'path': '/encryption',
    'title': 'Encryption',
    'sections': [
      [
        '',
        '',
        [
          'Everything is encrypted; only you, with your Secret Key, can see the content inside.',
          'In our apps, all your content is encrypted with your Secret Key. Only your encrypted content leaves your device to be stored on servers. At the same time, your Secret Key always stays in your device, ensuring that only you know your Secret Key. No one can see the content inside your encrypted content because only your Secret Key can decrypt it. Your encrypted data must be downloaded to your device to decrypt and access the content inside, hence end-to-end encryption. You can be assured that your encrypted content cannot be used to create targeted ads. Even if your encrypted content is stolen, no information is leaked.',
        ],
      ],
      [
        'Encryption Process',
        'encryption-process',
        [
          'Encryption involves a multi-step process that begins with generating a random number with a cryptographically secure random number generator. This random number selects 24 unique words from a predefined wordlist, forming a Secret Key. Then, a key derivation function named PBKDF2 is applied to the Secret Key, transforming it into a ~100-character string known as a private key. With the private key, an industry-standard encryption algorithm named AES-256-CBC is used to securely encrypt data.',
          'Also, the private key is the foundation for generating a public key and signing messages.',
        ],
      ],
      [
        'Encryption Algorithms',
        'encryption-algorithms',
        [
          'Cryptographically Secure Random Number Generator',
          'A Cryptographically Secure Random Number Generator (CSPRNG) is a specialized random number generator designed to produce sequences of numbers statistically indistinguishable from truly random numbers. CSPRNGs are specifically engineered to avoid such predictability, unlike ordinary random number generators, which may exhibit patterns or biases.',
          'The output of a CSPRNG should be impossible to predict based on past outputs or any other available information. This is crucial for cryptographic applications, as any predictability could be exploited by attackers to compromise the security of a system. Additionally, the sequence of numbers produced by a CSPRNG should exhibit statistical properties consistent with a truly random sequence, such as uniform distribution, no correlations, and passing various statistical tests. This ensures that the CSPRNG is not generating biased or predictable sequences of numbers. Finally, a CSPRNG should resist various attacks that could compromise its security, such as cryptanalysis or side-channel attacks.',
          'A CSPRNG is a crucial component of modern cryptography. It provides a reliable source of random numbers essential for ensuring cryptographic system security.',
          'PBKDF2',
          'PBKDF2 (Password-Based Key Derivation Function 2) is a cryptographic algorithm that transforms a relatively short password or passphrase into a longer, more complex cryptographic key. This derived key can be used for various cryptographic operations, such as encryption, decryption, or digital signing.',
          'PBKDF2 combines the password with a random salt value and then iteratively applies a pseudorandom function (PRF) to the resulting input. The number of iterations can be adjusted to control the computational cost of deriving the key, making it more resistant to brute-force attacks. The final output of PBKDF2 is a derived key of a desired length, typically 128, 192, or 256 bits.',
          "PBKDF2 is widely used due to its simplicity, security, and flexibility. It is relatively easy to implement and understand, making it a popular choice for various cryptographic applications. PBKDF2's iterative nature makes it resistant to brute-force attacks, even with powerful hardware. Additionally, PBKDF2 can be used with multiple PRFs and iteration counts, allowing customization to different security requirements.",
          'PBKDF2 is commonly used for password hashing, key derivation, and authentication. It hashes passwords before storing them in databases, making it more difficult for attackers to recover the original passwords. PBKDF2 can also derive cryptographic keys from user-provided passwords or passphrases for various cryptographic operations. Furthermore, PBKDF2 can be used in authentication protocols to verify the authenticity of users based on their passwords.',
          'AES-256-CBC',
          'AES-256-CBC (Advanced Encryption Standard with Cipher Block Chaining) is a robust and widely recognized encryption algorithm. It provides high security for data protection by encrypting data by breaking it into 16-byte blocks and applying complex mathematical operations to each block.',
          'The "256" in AES-256 refers to the key size, which is 256 bits long. A more extended key size makes it exponentially harder for an unauthorized party to crack the encryption, providing higher security.',
          'The "CBC" in AES-256-CBC stands for Cipher Block Chaining. This mode of operation links each encrypted block to the previous one, making it more difficult for attackers to identify patterns or weaknesses in the encryption. If one block is altered, it affects the decryption of subsequent blocks, making it less likely for an attacker to successfully tamper with the data.',
          'Using AES-256-CBC, your data is effectively scrambled and protected from unauthorized access. This encryption method is widely trusted and used in various applications, including secure messaging, online banking, and data storage.',
        ],
      ],
    ],
  },
  {
    'path': '/data-server',
    'title': 'Data Server',
    'sections': [
      [
        '',
        '',
        [
          'Your data lives in a data server of your choice; only you, with your Secret Key, can change it.',
          'You can choose where to store your data by using your Secret Key to record the location of your data server in the Stacks blockchain. Our apps will retrieve the information when you sign in and store your data on that specified server. You truly own your data as you can access, manage, and set permissions directly on your server. Only your Secret Key can change your information in the blockchain. No one can lock you out of your own data.',
        ],
      ],
      [
        'Stacks Data Server',
        'stacks-data-server',
        [
          "Brace.to stores your data in a Stacks data server. You can specify which Stacks data server to store your data in. By default, your Stacks data server is at hub.stacksdrive.com, provided by STX Apps. You can also deploy your own Stacks data server. To change your Stacks data server, you must record your server's information on the Stacks blockchain using your Secret Key. Brace.to retrieves the information from the blockchain when you sign in and store your data on that specified server. For more details, please visit Stacks Gaia.",
          'There has yet to be a user-friendly tool for deploying your own Stacks data server, managing its location on the Stacks blockchain, or directly handling files and setting permissions on the server. We plan to create a tool with these features and will update you on our progress.',
        ],
      ],
    ],
  },
  {
    'path': '/save-a-link',
    'title': 'Save a Link',
    'sections': [
      [
        '',
        '',
        [
          'There are several ways to save a link for your convenience. Just one or two clicks away to save any links on any of your devices.',
        ],
      ],
      [
        'Save at Brace.to',
        'save-at-brace-to',
        [
          "Click the '+ add' button on our website.",
        ],
      ],
      [
        'Save in Address Bar',
        'save-in-address-bar',
        [
          "Type 'brace.to' and '/' in front of any link in the web browser address bar.",
        ],
      ],
      [
        'Save with our Extension',
        'save-with-our-extension',
        [
          'Install our Chrome or Firefox web browser extension and click on our extension icon next to the address bar.',
        ],
      ],
      [
        'Save via our Mobile App',
        'save-via-our-mobile-app',
        [
          'Install our app from the Google Play or App Store on your device and share a link with it.',
        ],
      ],
    ],
  },
  {
    'path': '/organize-links',
    'title': 'Organize Links',
    'sections': [
      [
        '',
        '',
        [
          'Organize your links by moving them to Archive, Trash, or any list (folder) you create. In Settings -> Lists, you can create and organize lists (folders), such as arranging or moving into another list as needed.',
        ],
      ],
      [
        'Move Links',
        'move-links',
        [
          'There are two ways to move links:',
          "You can move a link by clicking the link three-dot menu and choosing 'Archive', 'Remove', or 'Move to'.",
          "To move multiple links simultaneously, click the 'Select' button in the top or bottom bar first. Select as many links as you want. Then, choose 'Archive', 'Remove', or 'Move to' in the top or bottom bar.",
        ],
      ],
      [
        'Create a New List',
        'create-a-new-list',
        [
          'Please go to Settings -> Lists to create a new list. Type a name in the text box and choose the OK (check) button. Your new list will be appended to the bottom of the others.',
        ],
      ],
      [
        'Organize Lists',
        'organize-lists',
        [
          'Also, in Settings -> Lists, you can:',
          'Edit a list name by clicking on the name.',
          "Arrange a list name with the 'up' or 'down' button.",
          "Move into another list with the 'Move to' button (creating nest lists or subfolders).",
          "Delete a list name with the 'Delete' button.",
          "Some buttons might be in the three-dot menu. Default lists — 'My List', 'Trash', and 'Archive' — can not be deleted. 'My list' is the default list when you save a link from the browser address bar, browser extension, or mobile app. Trash is for removed links only, and you can permanently delete them here.",
        ],
      ],
      [
        'Delete Links',
        'delete-links',
        [
          'Removed links in Trash will be automatically permanently deleted after 45 days. You can permanently delete any link in Trash immediately by:',
          "Click the 'Permanently delete' button under the link three-dot menu.",
          "To permanently delete multiple removed links, click the 'Select' button in the top or bottom bar first. Select as many removed links as you want. Then, choose the 'Permanently delete' button in the top or bottom bar.",
        ],
      ],
    ],
  },
  {
    'path': '/bookmark-manager-101',
    'title': 'Bookmark Manager',
    'sections': [
      [
        '',
        '',
        [
          "Bookmark managers or bookmarking apps do one thing: store links to everything you can visit later. This differs from read-later apps, which focus on storing articles to read later in the app, and note-taking apps, which aren't primarily designed with saving links in mind.",
        ],
      ],
      [
        'What is a Bookmark Manager?',
        'what-is-a-bookmark-manager',
        [
          'A bookmark manager is a software application or web service designed to help users organize, store, and access their bookmarks (favorites or links) efficiently. As the internet grows and people visit more websites, keeping track of important links becomes increasingly challenging. Bookmark managers provide a centralized location to store and manage all your bookmarked URLs, making it easier to find and revisit websites you frequently use or want to reference later.',
          'The primary purpose of a bookmark manager is to overcome the limitations of traditional browser bookmarking systems. Web browsers typically offer basic bookmarking features but lack advanced organization, search, and synchronization capabilities. Bookmark managers offer a more robust solution by allowing users to categorize bookmarks into folders, add descriptions or tags, search through their bookmarks, and sync them across multiple devices and browsers.',
        ],
      ],
      [
        'Using a Bookmark Manager Offers Several Benefits',
        'using-a-bookmark-manager-offers-several-benefits',
        [
          'Organization and Efficiency: Bookmark managers enable users to organize their bookmarks in a structured manner, making it easier to find and access specific websites when needed. This can significantly improve productivity and save time compared to navigating through a cluttered browser bookmarks folder.',
          'Cross-Platform Synchronization: Many bookmark managers offer cloud-based synchronization, allowing users to access their bookmarks seamlessly across different devices and platforms. This ensures that bookmarks are always available, regardless of the device or browser.',
          'Collaboration and Sharing: Some bookmark managers support sharing and collaboration features, enabling users to share bookmarks with others or access shared bookmark collections from colleagues, friends, or online communities.',
          'Backup and Restoration: Bookmark managers typically provide backup and restoration capabilities, ensuring that users can safeguard and restore their bookmarks in case of data loss or switching to a new device or browser.',
          'Advanced Search and Filtering: Bookmark managers often include powerful search and filtering tools, allowing users to quickly locate specific bookmarks based on titles, descriptions, tags, or other metadata.',
          'A bookmark manager is a valuable tool for anyone who frequently uses the internet and needs to efficiently organize, access, and share their bookmarked websites across multiple devices and platforms.',
        ],
      ],
      [
        'Security Risks of Bookmark Managers',
        'security-risks-of-bookmark-managers',
        [
          'Bookmark managers can pose significant security risks if not implemented and used correctly. One of the primary concerns is potential data breaches, where cybercriminals could gain unauthorized access to your bookmarks and sensitive information stored within them. This could include login credentials, financial data, or personal details that may be saved in the URLs or webpage content.',
          'Another risk is the possibility of vulnerabilities in the bookmark manager software itself. Like any application, bookmark managers may have security flaws or bugs that hackers could exploit to gain access to your data or even take control of your device. Keeping the software up-to-date with the latest security patches is crucial to mitigate these risks.',
          'Privacy is another concern, especially for cloud-based bookmark managers. If your bookmarks and browsing history are improperly encrypted, they could be exposed to the service provider or intercepted during transmission. This could lead to privacy breaches and potentially enable targeted advertising or profiling based on your online activities.',
          'Furthermore, suppose you share bookmark access with others or sync across multiple devices. If proper access controls and encryption are not in place, there is a risk of unauthorized access or data leaks. Malicious actors could gain access to your shared bookmarks or sync data, compromising your privacy and security.',
        ],
      ],
      [
        'Factors to Consider for a Secure Bookmark Manager',
        'factors-to-consider-for-a-secure-bookmark-manager',
        [
          'Several key factors should be considered when evaluating the security of a bookmark manager to ensure the protection of sensitive data and online activities.',
          'Encryption: Robust encryption is paramount for a secure bookmark manager. Look for solutions that employ end-to-end encryption, where your data is encrypted on your device before being transmitted and stored, ensuring that only you can access the decryption keys. Industry-standard encryption algorithms like AES-256 should be used to safeguard your data from unauthorized access.',
          'Password Management: A secure bookmark manager should incorporate strong password management capabilities. This includes generating and storing complex, unique passwords for each website or service you use, reducing the risk of password reuse, and making it harder for attackers to access your accounts. The bookmark manager should also be protected by a robust master password or passphrase.',
          'Two-Factor Authentication (2FA): Enabling two-factor authentication adds an extra layer of security by requiring a second form of verification, such as a one-time code or biometric authentication, in addition to your password. This significantly reduces the risk of unauthorized access, even if your password is compromised. Look for bookmark managers that support 2FA or integrate with popular 2FA apps or services.',
          'Data Storage Practices: Consider the data storage practices of the bookmark manager you choose. Self-hosted solutions, where you maintain control over the server and data storage, generally offer greater security and privacy than cloud-based services. However, cloud-based services may provide additional convenience and accessibility. If opting for a cloud-based solution, ensure that the provider follows industry-standard security practices, such as data encryption at rest and in transit, secure data centers, and regular security audits.',
          'By carefully evaluating these factors, you can select a bookmark manager that prioritizes security and protects sensitive information from potential threats, ensuring a safer and more secure online experience.',
        ],
      ],
      [
        'Open-Source vs. Proprietary Bookmark Managers',
        'open-source-vs-proprietary-bookmark-managers',
        [
          'One critical decision when choosing a secure bookmark manager is using an open-source or proprietary solution. Each approach has advantages and drawbacks regarding security, transparency, and community support.',
          'Open-Source Bookmark Managers',
          'Open-source bookmark managers have their source code publicly available, allowing anyone to review, modify, and contribute to the codebase. This level of transparency can be a significant advantage for security-conscious users, as the code can be scrutinized by security experts and the broader community for potential vulnerabilities.',
          'Pros:',
          'Transparency: The open-source nature of the software promotes transparency, allowing for independent security audits and peer review.',
          'Community Support: Open-source projects often have active communities of developers and users contributing to bug fixes, security patches, and feature enhancements.',
          'Customizability: Users with coding skills can modify the source code to suit their specific needs or preferences.',
          'No Vendor Lock-in: Open-source solutions are typically more flexible and less prone to vendor lock-in, making it easier to switch to alternative solutions if needed.',
          'Cons:',
          'Maintenance Burden: Relying on community contributions can sometimes lead to inconsistent or delayed maintenance and support.',
          'Security Risks: While open-source code can be scrutinized, potential vulnerabilities are publicly visible, which could be exploited by malicious actors.',
          'Proprietary Bookmark Managers',
          'Commercial entities develop and maintain proprietary bookmark managers, with the source code remaining closed and inaccessible to the public. These solutions often come with dedicated support and regular updates from the vendor.',
          'Pros:',
          'Dedicated Support: Proprietary solutions typically offer dedicated support channels and resources from the vendor.',
          'Regular Updates: Commercial vendors are vested in maintaining and updating their products, ensuring timely security patches and feature enhancements.',
          'User-Friendly Interfaces: Proprietary solutions often prioritize user-friendly interfaces and a polished user experience.',
          'Cons:',
          "Lack of Transparency: Access to the source code is necessary to independently verify proprietary solutions' security and privacy practices.",
          'Vendor Lock-in: Proprietary solutions can lead to vendor lock-in, making it difficult to switch to alternative solutions without significant effort or data migration challenges.',
          'Cost: Proprietary solutions often require paid subscriptions or licenses, which can be a recurring expense.',
          'Ultimately, the choice between open-source and proprietary bookmark managers depends on your specific security requirements, technical expertise, and willingness to trade transparency for dedicated support and a potentially more user-friendly experience.',
        ],
      ],
      [
        'Cloud-Based vs. Self-Hosted Bookmark Managers',
        'cloud-based-vs-self-hosted-bookmark-managers',
        [
          'When choosing a secure bookmark manager, one crucial decision is using a cloud-based or self-hosted solution. This choice significantly impacts data control, privacy, and overall security.',
          'Cloud-Based Bookmark Managers',
          'Cloud-based bookmark managers store your bookmarks and data on remote servers owned and managed by the service provider. This approach offers several advantages, including:',
          'Accessibility: You can access your bookmarks from any device with an internet connection, making it convenient for users who frequently switch between multiple devices or locations.',
          'Automatic Sync: Cloud-based services automatically sync your bookmarks across all your devices, ensuring you always have the latest version of your bookmarks.',
          'No Installation Required: Cloud-based solutions are typically accessible through a web interface or browser extension, eliminating the need for local installation and maintenance.',
          'However, cloud-based bookmark managers also come with potential drawbacks and security concerns:',
          'Data Privacy: Your bookmarks and browsing data are stored on third-party servers, which can raise privacy concerns, primarily if the service provider is based in a jurisdiction with lax data protection laws.',
          'Vendor Lock-in: You depend on the service provider, and if they discontinue their service or change their policies, you may face difficulties migrating your data.',
          'Potential Data Breaches: While reputable providers implement robust security measures, cloud-based services are still susceptible to possible data breaches or unauthorized access.',
          'Self-Hosted Bookmark Managers',
          'On the other hand, self-hosted bookmark managers involve installing and running the software on your own server or local machine. This approach offers greater control and privacy but requires more technical expertise and maintenance efforts. Critical advantages of self-hosted solutions include:',
          'Data Ownership and Control: You have complete control over your bookmarks and data, which are stored on your own infrastructure, reducing the risk of unauthorized access or data breaches.',
          'Privacy: Your browsing habits and bookmarks remain private, as they are not stored on third-party servers.',
          'Customization: Self-hosted solutions often offer more flexibility and customization options, allowing you to tailor the software to your needs.',
          'However, self-hosting also comes with its own set of challenges:',
          'Technical Expertise: Setting up and maintaining a self-hosted solution requires technical knowledge and experience, which may not be suitable for non-technical users.',
          'Maintenance and Updates: You are responsible for keeping the software up-to-date, applying security patches, and ensuring proper backups, which can be time-consuming and resource-intensive.',
          'Limited Accessibility: Self-hosted solutions may not be as easily accessible from multiple devices or locations, as they typically require a direct connection to the server or local network.',
          'Choosing a cloud-based or self-hosted bookmark manager depends on your specific requirements, technical expertise, and privacy and security priorities. Cloud-based solutions offer convenience and accessibility, while self-hosted options provide greater control and privacy at the cost of increased technical complexity.',
        ],
      ],
      [
        'Bookmark Manager Integration and Compatibility',
        'bookmark-manager-integration-and-compatibility',
        [
          "A crucial factor to consider when choosing a secure bookmark manager is its integration capabilities and compatibility across different platforms and tools. Cross-platform support ensures seamless access to your bookmarks from any device or operating system, whether you're using a desktop computer, laptop, tablet, or smartphone. This flexibility is precious in today's multi-device environment, allowing you to pick up where you left off without being tied to a single device.",
          'Additionally, many bookmark managers offer browser extensions or plugins that seamlessly integrate with popular web browsers like Google Chrome, Mozilla Firefox, Safari, and others. These extensions provide a convenient way to manage bookmarks directly from your browser, eliminating the need to switch between applications. They often include features like quick bookmark saving, search functionality, and easy access to your bookmark library.',
          'Furthermore, some bookmark managers integrate with other productivity tools and services, such as note-taking applications, task managers, or cloud storage platforms. This integration can streamline your workflow by allowing you to easily save and organize bookmarks alongside related notes, tasks, or files. For example, you might be able to save a bookmark and associated notes within the same application, making it easier to keep your research and ideas organized.',
          'When evaluating bookmark managers, consider the platforms and tools you commonly use and prioritize those that offer native support or robust integration capabilities. This seamless integration can significantly enhance your productivity and ensure a consistent experience across all your devices and workflows.',
        ],
      ],
      [
        'Bookmark Manager Backup and Sync Options',
        'bookmark-manager-backup-and-sync-options',
        [
          'Reliable backup and sync capabilities are essential for a secure bookmark manager. Data loss can be devastating, wiping out your carefully curated collection of bookmarks accumulated over years. A robust backup strategy ensures you can recover your data in case of hardware failure, software issues, or accidental deletion.',
          'Most bookmark managers offer automatic backup features, allowing you to schedule regular backups to a local drive, cloud storage, or both. Local backups provide an extra layer of protection against online threats, while cloud backups offer remote access and redundancy. Some bookmark managers even support version control, enabling you to revert to previous bookmark states if needed.',
          'Sync options are equally crucial, keeping your bookmarks up-to-date across multiple devices and ensuring a seamless experience. Many bookmark managers sync data in real time, instantly reflecting changes made on one device across all connected platforms. This feature is precious for those who access their bookmarks from various devices, such as a desktop computer, laptops, tablets, and smartphones.',
          'When evaluating bookmark managers, consider their backup and sync capabilities closely. Look for options that allow you to customize backup schedules, storage locations, and sync intervals. Additionally, consider managers that offer end-to-end encryption for backups and sync data, ensuring your bookmarks remain secure even if the backup or sync servers are compromised.',
        ],
      ],
      [
        'Bookmark Manager Security Best Practices',
        'bookmark-manager-security-best-practices',
        [
          'Proper security practices are crucial when using a bookmark manager to safeguard sensitive data and online accounts. Here are some essential tips to enhance the security of your bookmark manager:',
          'Strong and Unique Passwords:',
          'Use a strong password for your bookmark manager account.',
          'Avoid using the same password across multiple services, as this increases the risk of account compromise.',
          'Consider using a password manager to generate and store strong, randomized passwords.',
          'Two-Factor Authentication (2FA): Whenever available, enable two-factor authentication for an additional layer of security. 2FA requires a second factor, such as a one-time code sent to your phone or generated by an authenticator app, in addition to your password, making it much harder for unauthorized individuals to access your account.',
          'Encrypted Synchronization: If you sync your bookmarks across multiple devices, ensure the synchronization process is encrypted. This prevents your sensitive data from being intercepted during transmission.',
          'Regular Updates: Keep your bookmark manager software and any related extensions or plugins updated to the latest version. Software updates often include security patches that address known vulnerabilities.',
          'Careful Sharing: Be cautious when sharing bookmarks or bookmark collections with others. Only share sensitive information with trusted individuals or organizations, and consider using a separate, dedicated account for sharing purposes.',
          'Limit Access: Restrict access to your bookmark manager account on shared or public devices. Avoid logging in from untrusted or unsecured networks, as this increases the risk of compromised credentials.',
          'Regular Backups: Regularly back up your bookmarks to a secure location, such as an encrypted external drive or cloud storage service. This ensures you can restore your bookmarks in case of data loss or account compromise.',
          'Monitor for Suspicious Activity: Watch for suspicious activity related to your bookmark manager account, such as unauthorized logins or bookmark changes. If you suspect unauthorized access, change your password immediately and review your account settings.',
          'Following these security best practices can significantly reduce the risks of using a bookmark manager and protect your valuable online data and accounts.',
        ],
      ],
      [
        'Bookmark Manager Alternatives and Workarounds',
        'bookmark-manager-alternatives-and-workarounds',
        [
          'While bookmark managers offer a convenient way to organize and access your bookmarks across devices, some users may have specific needs or concerns that make alternatives appealing. Several workarounds and alternative solutions exist for those who prioritize privacy and simplicity or prefer a more manual approach.',
          'Browser Bookmarks: Most modern web browsers come with built-in bookmark management features. While less robust than dedicated bookmark managers, browser bookmarks can be a simple, privacy-focused solution for those with modest bookmark collections. This approach keeps your bookmarks locally stored and avoids reliance on third-party services.',
          'Plain Text Files: For those seeking an ultra-minimalist approach, plain text files can serve as a low-tech bookmark manager. By storing bookmark URLs and titles in a simple text file, you can easily access and edit your bookmarks using any text editor. This method offers complete control and portability but lacks advanced features like tagging and synchronization.',
          "Self-Hosted Web Archives: If you're concerned about data privacy and want complete control over your bookmarks, consider setting up a self-hosted web archives solution like Wallabag or Shaarli. These open-source applications allow you to save and organize web pages locally, creating your own private bookmark and archive system.",
          'Local File Managers: Depending on your operating system, you can leverage built-in file managers to organize and access bookmarks stored as local files or shortcuts. For example, on Windows, you can create a dedicated folder for bookmarks and use File Explorer to manage them. You can utilize the Finder, its tagging, and smart folder features on macOS.',
          'Bookmarklets and Browser Extensions: For those who prefer a more lightweight approach, bookmarklets and browser extensions can provide basic bookmark management functionality without needing a dedicated application. These small scripts or add-ons can save and organize bookmarks within your browser, offering a more integrated experience.',
          'Remember, choosing a bookmark manager or alternative solution ultimately depends on your needs, preferences, and comfort level with various technologies. While dedicated bookmark managers offer robust features and cross-device synchronization, alternatives like those mentioned above may better suit users prioritizing simplicity, privacy, or local control over their bookmarks.',
        ],
      ],
    ],
  },
  {
    'path': '/read-later-app-101',
    'title': 'Read-Later Apps',
    'sections': [
      [
        '',
        '',
        [
          "Read-later apps focus on storing articles to read later in the app, which differs from bookmarking apps and note-taking apps. The former is for store links to everything for you to visit later, and the latter isn't primarily designed to work with articles.",
        ],
      ],
      [
        'What is a Read-Later App?',
        'what-is-a-read-later-app',
        [
          "A read-later app is a software application or web service that lets you save online content—such as articles, videos, and even social media posts—to read or view at a more convenient time. These apps are great for organizing content you want to revisit, especially when you don't have time to engage immediately. Famous examples include Pocket, Instapaper, and Matter.",
          'A read-later app aims to streamline the reading experience by removing ads and distractions, providing clean, readable layouts, and allowing users to curate their content collections. Some apps even integrate with other platforms, so you can save items directly from your browser, social media, or RSS feeds into the app. They often include features for offline access, tagging for organization, and sometimes even highlighting or note-taking.',
        ],
      ],
      [
        'Using a Read-Later App Offers Several Benefits',
        'using-a-read-later-app-offers-several-benefits',
        [
          'Better Reading Experience: Read-later apps aim to streamline the reading experience by removing ads and distractions and providing clean, readable layouts.',
          'Organization and Efficiency: Read-later apps allow users to curate their content collections, enabling you to organize your content in a structured manner. This makes finding and accessing specific content easier when needed, significantly improving productivity and saving time.',
          'Integration: Some read-later apps integrate with other platforms, so you can save items directly from your browser, social media, or RSS feeds into the app.',
          'Synchronization: Many read-later apps offer cloud-based synchronization, allowing users to access their content seamlessly across different devices and platforms. This ensures that your content is always available, regardless of the device.',
          'Collaboration and Sharing: Some read-later apps support sharing and collaboration features, enabling users to share their content collections with others and access shared collections from colleagues, friends, or online communities.',
          'Backup and Restoration: Read-later apps typically provide backup and restoration capabilities, ensuring that users can safeguard and restore their content in case of data loss or switching to a new account.',
          'Advanced Search and Filtering: Read-later apps often include powerful search and filtering tools, allowing users to quickly locate specific content based on titles, descriptions, tags, or other metadata.',
        ],
      ],
      [
        'Security Risks of Read-Later Apps',
        'security-risks-of-read-later-apps',
        [
          'While convenient, read-later apps come with potential security and privacy risks. Here are a few key concerns to keep in mind:',
          "Data Privacy and Exposure: Read-later apps typically collect data about what users save, read, and interact with. If this information isn't handled securely, it could expose sensitive browsing habits or interests.",
          "Unauthorized Access: If your account on a read-later app isn't well-protected (e.g., weak password, no two-factor authentication), attackers could gain access, exposing your saved content or, worse, linked accounts (like social media or email accounts used for logging in).",
          "Malicious Content: Some read-later apps allow saving or previewing content from any online source. If the app doesn't have strong security measures, you could be exposed to harmful links or malicious scripts within the app.",
          "Third-Party Integrations: Many read-later apps integrate with other services, like email or social media, to make saving content easier. However, these connections can increase the risk surface. For instance, if one linked service experiences a data breach, it could also impact the read-later app's security.",
          'Data Breaches: Like any online service, cybercriminals could target read-later apps. A breach could expose user information, including saved content, email addresses, and linked account credentials.',
        ],
      ],
      [
        'Factors to Consider and Best Practices for a Secure Read-Later App',
        'factors-to-consider-and-best-practices-for-a-secure-read-later-app',
        [
          "Several key factors should be considered when evaluating a read-later app's security to protect sensitive data and online activities.",
          'Encryption: Robust encryption is paramount for a secure read-later app. Look for solutions that employ end-to-end encryption, where your data is encrypted on your device before being transmitted and stored, ensuring that only you can access the decryption keys. Industry-standard encryption algorithms like AES-256 should be used to safeguard your data from unauthorized access.',
          'Password Management: A secure read-later app should incorporate strong password management capabilities. This includes generating and storing complex, unique passwords for each website or service you use, reducing the risk of password reuse, and making it harder for attackers to access your accounts.',
          'Data Storage Practices: Consider the data storage practices of read-later apps. Self-hosted solutions, where you maintain control over the server and data storage, generally offer greater security and privacy than cloud-based services. However, cloud-based services may provide additional convenience and accessibility. If opting for a cloud-based solution, ensure that the provider follows industry-standard security practices, such as data encryption at rest and in transit, secure data centers, and regular security audits.',
          'Regular Updates: Keep your read-later app and any related extensions or plugins updated to the latest version. Software updates often include security patches that address known vulnerabilities.',
          'Regular Backups: Regularly back up your content to a secure location, such as an encrypted external drive or cloud storage service. This ensures you can restore your content in case of data loss or account compromise.',
          'Monitor for Suspicious Activity: Watch for suspicious activity related to your account, such as unauthorized logins or content changes. If you suspect unauthorized access, change your password immediately and review your account settings.',
          'By carefully evaluating these factors, you can select a read-later app that prioritizes security and protects sensitive information from potential threats, ensuring a safer and more secure online experience.',
        ],
      ],
      [
        'Open-Source vs. Proprietary Read-Later Apps',
        'open-source-vs-proprietary-read-later-apps',
        [
          'One critical decision when choosing a secure read-later app is using an open-source or proprietary solution. Each approach has advantages and drawbacks regarding security, transparency, and community support.',
          "Open-source read-later apps have their source code publicly available, allowing anyone to review, modify, and contribute to the codebase. This level of transparency can be a significant advantage for security-conscious users, as the code can be scrutinized by security experts and the broader community for potential vulnerabilities. It's also more flexible and less prone to vendor lock-in, making it easier to switch to alternative solutions if needed.",
        ],
      ],
      [
        'Read-Later App Integration and Compatibility',
        'read-later-app-integration-and-compatibility',
        [
          "A crucial factor to consider when choosing a secure read-later app is its integration capabilities and compatibility across different platforms and tools. Cross-platform support ensures seamless access to your content from any device or operating system, whether you're using a desktop computer, laptop, tablet, or smartphone. This flexibility is precious in today's multi-device environment, allowing you to pick up where you left off without being tied to a single device.",
          'Additionally, many read-later apps offer browser extensions or plugins that seamlessly integrate with popular web browsers like Google Chrome, Mozilla Firefox, Safari, and others. These extensions provide a convenient way to save content, such as an article, directly from your browser, eliminating the need to switch between applications. They often include features like search functionality and easy access to your content collections.',
          'When evaluating read-later apps, consider the platforms and tools you commonly use and prioritize those that offer native support or robust integration capabilities. This seamless integration can significantly enhance your productivity and ensure a consistent experience across all your devices and workflows.',
        ],
      ],
      [
        'Read-Later App Backup and Sync Options',
        'read-later-app-backup-and-sync-options',
        [
          'Reliable backup and sync capabilities are essential for a secure read-later app. Data loss can be devastating, wiping out your carefully curated content accumulated over years. A robust backup strategy ensures you can recover your data in case of hardware failure, software issues, or accidental deletion.',
          'Most read-later apps offer automatic backup features, allowing you to schedule regular backups to a local drive, cloud storage, or both. Local backups provide an extra layer of protection against online threats, while cloud backups offer remote access and redundancy.',
          'Sync options are equally crucial, keeping your content up-to-date across multiple devices and ensuring a seamless experience. Many read-later apps sync data in real time, instantly reflecting changes made on one device across all connected platforms. This feature is precious for those who access their content from various devices, such as desktop computers, laptops, tablets, and smartphones.',
          'When evaluating read-later apps, consider their backup and sync capabilities closely. Look for options that allow you to customize backup schedules, storage locations, and sync intervals. Additionally, consider apps that offer end-to-end encryption for backups and sync data, ensuring your content remains secure even if the backup or sync servers are compromised.',
        ],
      ],
    ],
  },
  {
    'path': '/faqs',
    'title': 'FAQs',
    'sections': [
      [
        'General',
        'general',
        [
          'How is Brace.to different from Raindrop, Pocket & Google Bookmarks?',
          'Brace.to is a privacy-focused bookmark manager. We offer end-to-end encryption with an encryption key only you know. Our app encrypts everything, including all your saved links, and only you can decrypt them and see the content inside.',
          'What are the benefits of using Brace.to?',
          'Your account cannot be locked, banned, or deleted by anyone, as it is cryptographically generated. Your Secret Key is required to access and modify it.',
          'No one can see the content inside your data, as everything is encrypted. Your data cannot be used to create targeted ads, and if your data is stolen, no information is leaked.',
          'You can manage your data and set permissions directly, as you can host your own data server or choose any data server provider.',
          'What do you mean by encrypting everything?',
          'Every file generated to store your data is encrypted, such as a file of a saved link and its information or a file of your app settings.',
          'How does end-to-end encryption work in Brace.to?',
          'Our app encrypts your data on your device with your Secret Key. Only your encrypted content leaves your device to be stored on servers. At the same time, your Secret Key always stays in your device, ensuring that only you know your Secret Key. No one can see the content inside your encrypted content because only your Secret Key can decrypt it. Your encrypted data must be downloaded to your device to decrypt and access the content inside.',
          'What are the benefits and drawbacks of only me knowing my Secret Key?',
          "It guarantees that only you can decrypt your data and see its content. But if you lose your Secret Key, it'll be lost forever, and no one can help you recover it.",
          'Do you store any data about my usage or run analytics?',
          'No, we take data privacy very seriously. There are no trackers, cookies, or fingerprinting done.',
          'Does Brace.to work on both web and mobile platforms?',
          'Yes. Our web app supports Chrome, Firefox, Safari, and similar browsers on desktops, smartphones, and tablets. We also have an iOS app on the App Store and an Android app on Google Play.',
          'Is Brace.to open source?',
          'Yes, our source code is published on GitHub.',
        ],
      ],
      [
        'Pricing',
        'pricing',
        [
          'How much does Brace.to cost?',
          'Brace.to is free, and we offer a simple, no-tricks subscription plan to unlock all extra features. Unlocking all extra features is around $4.99 per year with a 14-day free trial.',
          'What is the catch of the free tier? How long will it be free?',
          'Our business model is to create a lean, useful piece of software that grows with our users and can sustain us from every angle. The way everything is set up allows us to do that. If no one uses our service, it costs us almost nothing to run. If we have a lot of users, costs will go up, and so will revenue.',
          "We intend to keep all the current free features free forever and never show advertisements. We believe if our service is valuable, our users will support us. We wouldn't force it in any way. If users aren't ready, they can always close the popup and continue using our service.",
          'Does Brace.to show ads?',
          "No, we do not show ads. We intend to never show advertisements. We don't rent, sell, or share your information with other companies. Our optional paid subscription is the only way we make money.",
          'Can I cancel my subscription at any time?',
          'Yes, you can cancel your subscription anytime, no questions asked. You will still have access to extra features until your subscription expires.',
          'Do you offer a refund?',
          'No, we do not offer refunds, but you will be charged only after a 14-day trial period.',
          'What happens after my subscription expires?',
          'Everything will be the same, except you cannot use extra features. All existing data from extra features, such as pins or tags, will be there. You can also manage them but cannot create a new one.',
          'Lifetime plan?',
          "We're sorry, but we don't currently have a lifetime plan. We'll consider it. Our service has ongoing expenses, and we must be cautious with our pricing model for a sustainable business.",
          'Can I pay in BTC, ETH, STX, etc?',
          "We're sorry, but it's not possible right now. Our company relies on payment processing services for sale taxes and account booking.",
          "We'll keep an eye on it. Our payment processing services are constantly adding new payment methods (we believe cryptocurrencies are also in consideration). When they're available, we'll enable them in our app ASAP.",
          "I've subscribed, but I can't find it?",
          'If you visit Brace.to and extra features are still locked, please go to Settings -> Subscription -> Restore purchases. If the issue persists, please feel free to contact us.',
        ],
      ],
      [
        'Sign Up and Sign In',
        'sign-up-and-sign-in',
        [
          'What information is required for sign up?',
          'Nothing. We offer an anonymous sign-up; no personal information, such as an email address or credit card, is required.',
          "What's a Secret Key?",
          "A Secret Key acts like a password. You use it to access your account, and it's used to encrypt/decrypt your data. It's generated when you sign up and is only known to you, ensuring that only you can decrypt your data and see the content inside.",
          "You sign in on different devices with them. Make sure to save them somewhere safe. If you lose these words, you'll lose your account.",
          'Where should I save my Secret Key?',
          'Save your Secret Key in a place where only you can find it. For example:',
          'A password manager such as Bitwarden',
          'Your notes app, protected with a password',
          "Written down and kept somewhere safe\nDon't save it anywhere others can find it or on a website you do not trust. Anybody with your Secret Key will have access to your data.",
          "Why don't I have a password?",
          'Your Secret Key is your password. Multiple words are needed for the encryption mechanism and to prevent brute-force attacks.',
          'What if I lose my Secret Key?',
          "If you lose your Secret Key, it'll be lost forever. Only you know your Secret Key to ensure that only you can decrypt your data, which means no one can help you recover it.",
          'When will I need my Secret Key?',
          "You'll need your Secret Key to access your account, such as when you sign in on different devices, such as your new phone or laptop.",
          'Can I change or reset my Secret Key?',
          "Your Secret Key cannot be changed or reset. As it's used to encrypt your content file by file, if you change your Secret Key, every file needs to be decrypted with your old Secret Key and encrypted again with your new Secret Key.",
          'What can I do if I lose my Secret Key?',
          "If you've signed in on any device and you can still access it, we recommend:",
          'Export all your data (Settings -> Data -> Export All Data)',
          'Create a new account',
          'Import your data from the exported file (Settings -> Data -> Import Data)',
        ],
      ],
      [
        'Features',
        'features',
        [
          'Why do my links not show the names or display images?',
          "Extracting the title and image from a link takes some time, usually less than one hour. Links' titles and images will be shown after the extraction is complete.",
          'How does Brace.to get the name and image of a link?',
          'Our app sends the link to our server to extract the title and image. We send it without other information, and this feature can be disabled.',
          "Sometimes, our server might retrieve incorrect link titles or images as some websites think we're bots or crawlers and block us, or some guide us to the bad ones to use. We open-source our retrieval logic on GitHub, and we'll keep improving it.",
          'Can I create new folders and subfolders or lists and nested lists?',
          'Yes, please go to Settings -> Lists. You can create a new list and move it into any list.',
          'Can I choose a card layout on my desktop and a list layout on my phone?',
          'Yes, you can have a different layout on each device. To do so, go to Settings -> Misc. -> Layout View and select "Device" first.',
          'Does Brace.to have a dark mode/dark theme?',
          "Yes, we do. You can change the app's appearance in Settings -> Misc. Our dark is dark grey, not true black or AMOLED black.",
          'Can I share my lists?',
          "We're sorry it's impossible now. All data are encrypted, and only you can decrypt them and see the content inside. We'll also need to consider laws and regulations. As a company, we might need to block or remove some content. (We don't want to, but we need to comply.)",
        ],
      ],
    ],
  },
];